import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';

const $ = (s)=>document.querySelector(s);
const canvas=$('#scene'), stage=$('.stage'), phaseEl=$('#phase'), hint=$('#hint'), result=$('#result'), debug=$('#debug'), residualEl=$('#residual'), territoryBadge=$('#territoryBadge'), runtimeError=$('#runtimeError');
const trigger=$('#explainTrigger'), panel=$('#explainPanel'), backdrop=$('#explainBackdrop'), closeBtn=$('#explainClose');
const titleEl=$('#explainTitle'), leadEl=$('#explainLead'), stepsEl=$('#explainSteps'), advComparison=$('#advancedComparison'), advResidual=$('#advancedResidual'), advGeometry=$('#advancedGeometry');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;

const BLUE=0x1547a3, IVORY=0xf3f0e6, IVORY2=0xe9e3d8, VERMILION=0xe03a23;
const CLAIMS={LOCAL:[-.16,.21,-.06,.29,-.12,.18,-.03],EXTERNAL:[.23,-.17,.14,-.05,.26,-.11,.11]};
const ACCEPTED='LOCAL';

const TERRITORIES={
  hull:{name:'HULL',subtitle:'CIVIC GRID',badge:'HULL · CIVIC GRID',descriptor:'dense / compressed field',seed:17,labels:[['MONTCLAIR',.55,.23],['ST-JOSEPH',.75,.68],['DUFFERIN',.43,.48],['WELLINGTON',.68,.81]],path:[[-1.5,-.10],[-1.17,-.10],[-1.05,.03],[-.82,.03],[-.68,-.13],[-.35,-.13],[-.22,.02],[.12,.02],[.28,-.08],[.62,-.08],[.75,.08],[1.55,.08]],destPath:[[-1.55,.08],[-1.08,.08],[-.96,-.05],[-.62,-.05],[-.48,.10],[-.05,.10],[.10,-.02],[.53,-.02],[.66,.09],[1.5,.09]],field:'grid'},
  gatineau:{name:'GATINEAU',subtitle:'LINEAR CORRIDOR',badge:'GATINEAU · LINEAR CORRIDOR',descriptor:'directional / corridor field',seed:31,labels:[['RAPIBUS',.54,.23],['MALONEY',.23,.74],['DE LA CITÉ',.73,.47],['GRÉBER',.31,.52]],path:[[-1.55,-.04],[-.95,-.04],[-.77,-.04],[-.58,.02],[-.38,.02],[-.20,-.04],[.20,-.04],[.38,.01],[.72,.01],[1.55,.01]],destPath:[[-1.55,.01],[-1.12,.01],[-.74,.01],[-.54,-.04],[-.22,-.04],[.02,.02],[.42,.02],[.72,-.02],[1.50,-.02]],field:'corridor'},
  eastern:{name:'EASTERN PAIR',subtitle:'DISTRIBUTED LINK',badge:'EASTERN PAIR · DISTRIBUTED LINK',descriptor:'two nodes / connected field',seed:53,labels:[['BUCKINGHAM',.25,.28],['MASSON-ANGERS',.65,.30],['LORRAIN',.52,.77]],path:[[-1.50,.38],[-1.12,.30],[-.88,.17],[-.58,.03],[-.30,-.14],[.05,-.14],[.28,-.03],[.55,.05],[.88,.17],[1.55,.02]],destPath:[[-1.55,.02],[-1.17,.18],[-.90,.22],[-.55,.38],[-.20,.25],[.08,.10],[.38,.18],[.70,.34],[1.45,.42]],field:'pair'}
};

const S={territory:'hull',claim:'local',phase:'idle',drag:false,done:false,auto:false,debug:false,inspect:false,compatible:true};
let renderer,scene,cam,world,card,dest,cardBody,destBody,cardSurface,destSurface,cardTex,destTex,pathGroup,destPathGroup,core,profileGroup;
let layout={},dragTarget=new THREE.Vector3(),velocity=new THREE.Vector3(),registeredAt=0,rejectedAt=0,last=performance.now(),profileOpacity=0,inspectMix=0;
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),dragPlane=new THREE.Plane(new THREE.Vector3(0,0,1),0),hit=new THREE.Vector3(),offset=new THREE.Vector3();

const labels={idle:'GRAB THE CREDENTIAL',dragging:'MOVE TOWARD CITY FIELD',awareness:'RELATIONSHIP DETECTED',profile:'CLAIM × FIELD',compare:'COMPARING RELATIONSHIP',registered:'REGISTERED',continuing:'PASSAGE CONTINUING',revealed:'CITY PASSAGE REGISTERED',interference:'RELATIONSHIP DOES NOT REGISTER',rejected:'NO REGISTERED RELATIONSHIP',inspect:'INSPECTING RELATION'};
function setPhase(p){S.phase=p;phaseEl.textContent=labels[p]||p.toUpperCase();phaseEl.className='phase'+(['registered','continuing','revealed','inspect'].includes(p)?' registered':'')}
function roundedShape(w,h,r){const x=-w/2,y=-h/2,s=new THREE.Shape();s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function roundedBody(w,h,d,r,color){const geo=new THREE.ExtrudeGeometry(roundedShape(w,h,r),{depth:d,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.017,bevelThickness:.011,curveSegments:12});geo.center();return new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,roughness:.9,metalness:0}))}
function surface(w,h,texture,z=.061){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false}));m.position.z=z;return m}
function seeded(seed){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^t>>>15,1|t);r^=r+Math.imul(r^r>>>7,61|r);return((r^r>>>14)>>>0)/4294967296}}
function makeTexture(draw){const c=document.createElement('canvas');c.width=1000;c.height=620;draw(c.getContext('2d'),c);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
function text(ctx,value,x,y,size=24,weight=700,color='#1547a3',align='left'){ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='top';ctx.font=`${weight} ${size}px Arial`;ctx.fillText(value,x,y)}
function drawField(ctx,t){const rand=seeded(t.seed);ctx.save();ctx.strokeStyle='rgba(21,71,163,.22)';ctx.lineWidth=1.4;if(t.field==='grid'){for(let i=0;i<19;i++){const x=90+i*44+rand()*18;ctx.beginPath();ctx.moveTo(x,105);ctx.lineTo(x+rand()*26-13,540);ctx.stroke()}for(let i=0;i<12;i++){const y=145+i*31+rand()*12;ctx.beginPath();ctx.moveTo(65,y);ctx.lineTo(940,y+rand()*18-9);ctx.stroke()}}else if(t.field==='corridor'){for(let i=0;i<5;i++){ctx.beginPath();let y=250+i*26;ctx.moveTo(55,y);for(let x=55;x<=945;x+=90)ctx.lineTo(x,y+Math.sin((x+i*37)/120)*12);ctx.stroke()}for(let i=0;i<9;i++){const x=125+i*100;ctx.beginPath();ctx.moveTo(x,170-rand()*40);ctx.lineTo(x+rand()*40-20,475+rand()*50);ctx.stroke()}ctx.strokeStyle='rgba(21,71,163,.13)';for(let i=0;i<9;i++){ctx.beginPath();ctx.moveTo(40,80+i*8);for(let x=40;x<950;x+=40)ctx.lineTo(x,80+i*8+Math.sin(x/37+i)*5);ctx.stroke()}}else{const centers=[[245,310],[750,315]];for(const [cx,cy] of centers){for(let i=0;i<28;i++){const a=rand()*Math.PI*2,r=30+rand()*170;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.stroke()}}ctx.lineWidth=2.2;ctx.strokeStyle='rgba(21,71,163,.3)';ctx.beginPath();ctx.moveTo(250,310);ctx.lineTo(500,395);ctx.lineTo(750,315);ctx.stroke()}ctx.restore();t.labels.forEach(([label,px,py])=>text(ctx,label,px*1000,py*620,18,700,'rgba(21,71,163,.78)'))}
function drawCredentialTexture(){const t=TERRITORIES[S.territory];return makeTexture((ctx)=>{ctx.clearRect(0,0,1000,620);drawField(ctx,t);text(ctx,'CULTURAL EDITION',55,48,19,700,'#121212');text(ctx,'YOUTH PASS',55,79,15,700,'#6f6962');text(ctx,t.name,55,122,t.name.length>10?48:62,800,'#1547a3');text(ctx,t.subtitle,55,t.name.length>10?182:196,23,700,'#1547a3');text(ctx,S.claim==='local'?'LOCAL CLAIM':'EXTERNAL CLAIM',55,487,21,800,S.claim==='local'?'#e03a23':'#6f6962');text(ctx,'MEMBER · RK-CITY-017',55,530,16,600,'#756f68')})}
function drawDestinationTexture(){const t=TERRITORIES[S.territory];return makeTexture((ctx)=>{ctx.clearRect(0,0,1000,620);drawField(ctx,t);text(ctx,'CITY FIELD',55,48,19,700,'#121212');text(ctx,'REGISTRATION RULE',55,84,15,700,'#777067');text(ctx,t.name,55,126,t.name.length>10?44:58,800,'#1547a3');text(ctx,'LOCAL CLAIM ACCEPTED',55,209,26,800,'#e03a23');text(ctx,'PASSAGE EXISTS ONLY AFTER REGISTRATION',55,530,15,700,'#6f6962')})}
function refreshTextures(){if(cardTex)cardTex.dispose();if(destTex)destTex.dispose();cardTex=drawCredentialTexture();destTex=drawDestinationTexture();cardSurface.material.map=cardTex;destSurface.material.map=destTex;cardSurface.material.needsUpdate=true;destSurface.material.needsUpdate=true;territoryBadge.textContent=TERRITORIES[S.territory].badge;territoryBadge.dataset.territory=S.territory}
function tube(points,r,color,opacity=1){const curve=new THREE.CatmullRomCurve3(points.map(([x,y])=>new THREE.Vector3(x,y,.09)));return new THREE.Mesh(new THREE.TubeGeometry(curve,48,r,6,false),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false}))}
function rebuildPaths(){pathGroup.clear();destPathGroup.clear();const t=TERRITORIES[S.territory];pathGroup.add(tube(t.path,.027,BLUE,1));destPathGroup.add(tube(t.destPath,.027,BLUE,.04))}
function sphere(r,color,opacity=1){return new THREE.Mesh(new THREE.SphereGeometry(r,18,12),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false}))}
function profileResidual(a,b){return a.reduce((s,v,i)=>s+Math.abs(v-b[i]),0)/a.length}
function claimProfile(){return S.claim==='local'?CLAIMS.LOCAL:CLAIMS.EXTERNAL}
function residual(){return profileResidual(claimProfile(),CLAIMS[ACCEPTED])}
function biggestMismatch(a,b){let idx=0,max=0;for(let i=0;i<a.length;i++){const d=Math.abs(a[i]-b[i]);if(d>max){idx=i;max=d}}return{idx,delta:a[idx]-b[idx],max}}
function clearProfiles(){while(profileGroup.children.length){const m=profileGroup.children.pop();m.geometry?.dispose();m.material?.dispose?.()}}
function anchors(){return{a:new THREE.Vector3(card.position.x+1.67,card.position.y+.03,.10),b:new THREE.Vector3(dest.position.x-1.60,dest.position.y+.03,.10)}}
function gap(){const {a,b}=anchors();return a.distanceTo(b)}
function setProfileGeometry(opacity=1,spread=0){clearProfiles();const A=claimProfile(),B=CLAIMS[ACCEPTED],{a,b}=anchors();for(let i=0;i<A.length;i++){const t=i/(A.length-1)-.5,pa=a.clone().add(new THREE.Vector3(0,A[i]*.68+t*.03,.02+spread*A[i]*.12)),pb=b.clone().add(new THREE.Vector3(0,B[i]*.68+t*.03,.02-spread*B[i]*.12));const ca=sphere(.027,BLUE,opacity),cb=sphere(.027,VERMILION,opacity);ca.position.copy(pa);cb.position.copy(pb);profileGroup.add(ca,cb);const mid=pa.clone().lerp(pb,.5),bend=(A[i]-B[i])*.52;mid.y+=bend;mid.z=.13+Math.abs(bend)*.07;const curve=new THREE.CatmullRomCurve3([pa,mid,pb]);profileGroup.add(new THREE.Mesh(new THREE.TubeGeometry(curve,18,.009,5,false),new THREE.MeshBasicMaterial({color:S.compatible?VERMILION:0x8d8279,transparent:true,opacity:opacity*.88,depthWrite:false})))} }
function setup(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();cam=new THREE.PerspectiveCamera(34,1,.1,60);cam.position.set(0,0,8.7);scene.add(new THREE.HemisphereLight(0xffffff,0xd5ccbc,2.7));const key=new THREE.DirectionalLight(0xffffff,3.4);key.position.set(-3.5,5.5,6);scene.add(key);const rim=new THREE.DirectionalLight(0xffb49e,.75);rim.position.set(5,-2,4);scene.add(rim);world=new THREE.Group();scene.add(world);card=new THREE.Group();dest=new THREE.Group();world.add(card,dest);cardBody=roundedBody(3.34,2.1,.095,.17,IVORY);destBody=roundedBody(3.20,2.1,.095,.17,IVORY2);card.add(cardBody);dest.add(destBody);cardTex=drawCredentialTexture();destTex=drawDestinationTexture();cardSurface=surface(3.23,1.99,cardTex,.066);destSurface=surface(3.09,1.99,destTex,.066);card.add(cardSurface);dest.add(destSurface);pathGroup=new THREE.Group();destPathGroup=new THREE.Group();card.add(pathGroup);dest.add(destPathGroup);rebuildPaths();core=new THREE.Mesh(new THREE.CircleGeometry(.18,44),new THREE.MeshBasicMaterial({color:VERMILION,transparent:true,opacity:0}));core.position.z=.11;world.add(core);profileGroup=new THREE.Group();world.add(profileGroup);relayout();resize();renderer.render(scene,cam);requestAnimationFrame(loop)}
function relayout(){layout={start:new THREE.Vector3(-2.80,0,0),dest:new THREE.Vector3(2.58,0,0),snap:new THREE.Vector3(-.80,0,0)};if(innerWidth<720){world.scale.setScalar(.79);cam.position.z=9.6}else{world.scale.setScalar(1);cam.position.z=8.7}reset()}
function reset(){S.drag=false;S.done=false;S.auto=false;S.inspect=false;S.compatible=S.claim==='local';registeredAt=rejectedAt=0;profileOpacity=0;inspectMix=0;card.position.copy(layout.start);dest.position.copy(layout.dest);dragTarget.copy(layout.start);velocity.set(0,0,0);card.rotation.set(0,0,0);dest.rotation.set(0,0,0);core.material.opacity=0;result.hidden=true;trigger.hidden=true;residualEl.hidden=true;hint.classList.remove('hidden');clearProfiles();rebuildPaths();refreshTextures();setPhase('idle');closePanel(false)}
function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);cam.aspect=r.width/r.height;cam.updateProjectionMatrix()}
function spring(dt){const stiffness=reduced?120:58,damping=reduced?30:12.5;const force=dragTarget.clone().sub(card.position).multiplyScalar(stiffness);velocity.addScaledVector(force,dt);velocity.multiplyScalar(Math.exp(-damping*dt));card.position.addScaledVector(velocity,dt)}
function ndc(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,cam)}
function runAuto(){reset();S.auto=true;hint.classList.add('hidden');setPhase('awareness')}
function show(ok){const t=TERRITORIES[S.territory];result.hidden=false;result.innerHTML=ok?`<div class="result-kicker">RELATIONSHIP REGISTERED</div><div class="result-title">CITY PASSAGE REGISTERED</div><div class="result-detail">${t.name} · Local claim → city field → passage</div>`:`<div class="result-kicker">RELATIONSHIP DOES NOT REGISTER</div><div class="result-title small">NO REGISTERED RELATIONSHIP</div><div class="result-detail">The credential remains valid. This city field cannot register its current claim.</div>`;residualEl.textContent=ok?'ZERO':'PERSISTS';trigger.textContent=ok?'WHY THIS WORKS':'SEE WHY';trigger.hidden=false;renderPanel(ok)}
function renderPanel(ok){const t=TERRITORIES[S.territory];titleEl.textContent=ok?'Why this works':'Why it didn’t register';leadEl.textContent=ok?`The credential carries a local claim. ${t.name} supplies the matching city-field rule, so the interrupted path can continue.`:`The credential remains valid, but its current claim cannot register with the ${t.name} city field.`;const steps=ok?[["Credential claim","Local claim","The member carries a claim designed for this city field"],["Territory field",t.name,`The ${t.subtitle.toLowerCase()} geometry supplies the counterpart`],["Registration","Zero residual","The two profiles register at the junction"],["Outcome","City passage registered","The same path continues through the field"]]:[["Credential claim","External claim","The member carries a different relationship profile"],["Territory field",t.name,`The ${t.subtitle.toLowerCase()} geometry still expects a local claim`],["Registration","Residual persists","The profiles do not register"],["Outcome","No registered relationship","The credential remains valid; the path does not continue"]];stepsEl.innerHTML=steps.map((s,i)=>`<div class="explain-step"><div class="explain-index">0${i+1}</div><div><span>${s[0]}</span><strong>${s[1]}</strong><small>${s[2]}</small></div></div>`).join('');advComparison.textContent=`${S.claim==='local'?'LOCAL':'EXTERNAL'} claim × ${t.name} city field`;advResidual.textContent=ok?'Zero':'Persists';advGeometry.textContent=ok?'Registered continuation':`Interference + recoil · ${t.descriptor}`}
function openPanel(){if(result.hidden)return;S.inspect=true;backdrop.hidden=false;requestAnimationFrame(()=>{backdrop.classList.add('open');panel.classList.add('open');panel.setAttribute('aria-hidden','false');document.body.classList.add('explain-open')});setTimeout(()=>closeBtn.focus(),180)}
function closePanel(focus=true){S.inspect=false;backdrop.classList.remove('open');panel.classList.remove('open');panel.setAttribute('aria-hidden','true');document.body.classList.remove('explain-open');setTimeout(()=>{backdrop.hidden=true;if(focus&&!trigger.hidden)trigger.focus()},320)}
canvas.addEventListener('pointerdown',e=>{if(S.done||S.inspect)return;ndc(e);if(ray.intersectObject(cardBody).length){S.drag=true;S.auto=false;canvas.setPointerCapture(e.pointerId);ray.ray.intersectPlane(dragPlane,hit);offset.copy(card.position).sub(hit);hint.classList.add('hidden');setPhase('dragging')}});
canvas.addEventListener('pointermove',e=>{if(!S.drag||S.done)return;ndc(e);ray.ray.intersectPlane(dragPlane,hit);hit.add(offset);hit.y=THREE.MathUtils.clamp(hit.y,-.66,.66);hit.x=THREE.MathUtils.clamp(hit.x,layout.start.x-.12,layout.snap.x+.06);dragTarget.copy(hit)});
canvas.addEventListener('pointerup',e=>{S.drag=false;try{canvas.releasePointerCapture(e.pointerId)}catch{}if(!S.done)setPhase('idle')});
canvas.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!S.done){e.preventDefault();runAuto()}});
$('#reset').onclick=reset;$('#auto').onclick=runAuto;trigger.onclick=openPanel;closeBtn.onclick=()=>closePanel(true);backdrop.onclick=()=>closePanel(true);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('open'))closePanel(true)});
$('#debugToggle').onclick=e=>{S.debug=!S.debug;debug.hidden=!S.debug;e.currentTarget.setAttribute('aria-pressed',String(S.debug))};
document.querySelectorAll('[data-territory]').forEach(btn=>btn.onclick=()=>{S.territory=btn.dataset.territory;document.querySelectorAll('[data-territory]').forEach(x=>{x.classList.toggle('active',x===btn);x.setAttribute('aria-pressed',String(x===btn))});reset()});
document.querySelectorAll('[data-claim]').forEach(btn=>btn.onclick=()=>{S.claim=btn.dataset.claim;document.querySelectorAll('[data-claim]').forEach(x=>{x.classList.toggle('active',x===btn);x.setAttribute('aria-pressed',String(x===btn))});reset()});
window.addEventListener('resize',()=>{const small=innerWidth<720;world.scale.setScalar(small?.79:1);cam.position.z=small?9.6:8.7;resize()});
function loop(t){try{resize();const dt=Math.min(.032,(t-last)/1000||.016);last=t;const g=gap();if(S.auto&&!S.done)dragTarget.lerp(layout.snap,.024);const engaged=S.drag||S.auto;if(!S.done&&engaged){if(g<1.42&&g>.9)setPhase('awareness');if(g<=.9&&g>.36){setPhase('profile');profileOpacity=THREE.MathUtils.lerp(profileOpacity,1,.12)}if(g<=.36&&g>.15){setPhase('compare');profileOpacity=1;dragTarget.lerp(layout.snap,.12)}if(g<=.15){S.done=true;S.drag=false;S.auto=false;if(S.compatible){dragTarget.copy(layout.snap);registeredAt=t;setPhase('registered');navigator.vibrate?.(14)}else{const m=biggestMismatch(claimProfile(),CLAIMS[ACCEPTED]);const r=layout.snap.clone();r.y+=Math.sign(m.delta||1)*.28;r.x-=.18;dragTarget.copy(r);velocity.y+=Math.sign(m.delta||1)*1.25;rejectedAt=t;setPhase('interference');navigator.vibrate?.([8,18,8])}}}spring(dt);if((engaged&&g<.95)||S.done||S.inspect)setProfileGeometry(Math.max(.18,profileOpacity||.85),S.inspect?1:0);else clearProfiles();if(registeredAt){const x=(t-registeredAt)/1000;if(x>.14)core.material.opacity=.96;const mat=destPathGroup.children[0]?.material;if(mat)mat.opacity=Math.min(1,Math.max(.04,(x-.18)/.62));if(x>.34)setPhase('continuing');if(x>.86&&result.hidden){setPhase('revealed');show(true)}}if(rejectedAt){const x=(t-rejectedAt)/1000;if(x>.30&&result.hidden){setPhase('rejected');show(false)}}inspectMix=THREE.MathUtils.damp(inspectMix,S.inspect?1:0,reduced?100:6,dt);cam.position.x=THREE.MathUtils.damp(cam.position.x,S.inspect?.68:0,reduced?100:5.2,dt);cam.position.z=THREE.MathUtils.damp(cam.position.z,S.inspect?8.0:(innerWidth<720?9.6:8.7),reduced?100:5.2,dt);cam.lookAt(0,0,0);const {a,b}=anchors();core.position.copy(a.clone().lerp(b,.5));if(S.debug)debug.textContent=`TERRITORY ${TERRITORIES[S.territory].name}\nCLAIM ${S.claim.toUpperCase()}\nGAP ${g.toFixed(3)}\nRESIDUAL ${residual().toFixed(3)}\nSTATE ${S.phase}`;renderer.render(scene,cam);requestAnimationFrame(loop)}catch(err){console.error(err);runtimeError.hidden=false;phaseEl.textContent='RUNTIME ERROR'}}
try{setup()}catch(err){console.error(err);runtimeError.hidden=false;phaseEl.textContent='3D INITIALIZATION ERROR'}
