import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
const q=s=>document.querySelector(s), canvas=q('#scene'), stage=q('.stage'), phase=q('#phase'), result=q('#result'), debug=q('#debug');
const S={scenario:'family',phase:'idle',drag:false,done:false,auto:false,debug:false};
const R=new THREE.WebGLRenderer({canvas,antialias:true});R.setPixelRatio(Math.min(devicePixelRatio,1.5));R.setClearColor(0x0b0b0d);const scene=new THREE.Scene(),cam=new THREE.PerspectiveCamera(38,1,.1,50);cam.position.z=7.1;scene.add(new THREE.AmbientLight(0xffffff,2));const L=new THREE.DirectionalLight(0xffffff,2);L.position.set(3,4,5);scene.add(L);
const G=new THREE.Group();scene.add(G);const matCard=new THREE.MeshStandardMaterial({color:0x0c22e8,roughness:.8}),matDest=new THREE.MeshStandardMaterial({color:0xeee9de,roughness:.85}),orange=new THREE.MeshBasicMaterial({color:0xe84020});const card=new THREE.Mesh(new THREE.BoxGeometry(3.2,2.02,.075),matCard),dest=new THREE.Mesh(new THREE.BoxGeometry(3.04,2.02,.075),matDest);G.add(card,dest);
const pathA=new THREE.Mesh(new THREE.BoxGeometry(2.85,.04,.02),orange),pathB=new THREE.Mesh(new THREE.BoxGeometry(2.7,.04,.02),orange);G.add(pathA,pathB);const core=new THREE.Mesh(new THREE.CircleGeometry(.18,40),orange);core.visible=false;G.add(core);
function arc(side,bad=false){const g=new THREE.RingGeometry(.17,.22,40,1,side==='a'?-Math.PI/2:Math.PI/2,Math.PI);return new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:bad?0x6f6d68:0xe84020,side:THREE.DoubleSide}))}let a=arc('a'),b=arc('b');G.add(a,b);
let mobile=false,layout={},target=new THREE.Vector3(),t0=0,tReject=0;const ray=new THREE.Raycaster(),pt=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,0,1),0),hit=new THREE.Vector3(),offset=new THREE.Vector3();
const labels={idle:'GRAB THE CREDENTIAL',dragging:'MOVE TOWARD DESTINATION',awareness:'AWARENESS',proximity:'PROXIMITY',magnetic:'MAGNETIC FIELD',comparing:'COMPARING',registered:'REGISTERED',continuing:'CONTINUING',revealed:'ENTITLEMENT',resist:'RESIST',rejected:'NO RECIPROCAL RELATIONSHIP'};
function setPhase(p){if(S.phase===p)return;S.phase=p;phase.textContent=labels[p];phase.className='phase'+(p==='revealed'?' success':'')}
function layoutNow(){mobile=innerWidth<720;layout=mobile?{start:new THREE.Vector3(0,1.6,0),dest:new THREE.Vector3(0,-1.45,0),snap:new THREE.Vector3(0,.57,0)}:{start:new THREE.Vector3(-2.55,0,0),dest:new THREE.Vector3(2.45,0,0),snap:new THREE.Vector3(-.67,0,0)};reset()}
function positionStatic(){dest.position.copy(layout.dest);if(mobile){pathA.geometry.dispose();pathA.geometry=new THREE.BoxGeometry(.04,1.75,.02);pathB.geometry.dispose();pathB.geometry=new THREE.BoxGeometry(.04,1.7,.02);pathA.position.set(-.28,card.position.y-.12,.055);pathB.position.set(-.28,dest.position.y-.12,.055);a.position.set(-.28,card.position.y-1.01,.06);b.position.set(-.28,dest.position.y+1.01,.06);core.position.set(-.28,dest.position.y+1.01,.065)}else{pathA.geometry.dispose();pathA.geometry=new THREE.BoxGeometry(2.85,.04,.02);pathB.geometry.dispose();pathB.geometry=new THREE.BoxGeometry(2.7,.04,.02);pathA.position.set(card.position.x-.12,.04,.055);pathB.position.set(dest.position.x-.17,.04,.055);a.position.set(card.position.x+1.6,.04,.06);b.position.set(dest.position.x-1.52,.04,.06);core.position.set(dest.position.x-1.52,.04,.065)}}
function setArcs(bad){G.remove(a,b);a.geometry.dispose();b.geometry.dispose();a=arc('a',bad);b=arc('b',bad);G.add(a,b);positionStatic()}
function reset(){S.drag=false;S.done=false;S.auto=false;t0=tReject=0;card.position.copy(layout.start);target.copy(layout.start);card.rotation.set(0,0,0);core.visible=false;pathB.scale.set(mobile?1:.001,mobile?.001:1,1);result.hidden=true;setArcs(false);setPhase('idle')}
function gap(){return mobile?Math.max(0,(card.position.y-1.01)-(dest.position.y+1.01)):Math.max(0,(dest.position.x-1.52)-(card.position.x+1.6))}
function show(ok){result.hidden=false;result.innerHTML=ok?'<div class="result-kicker">RELATIONSHIP REGISTERED</div><div class="result-title">COMPLIMENTARY ADMISSION</div><div class="result-detail">Anchorage Museum <i>→</i> Family Plus <i>→</i> ROAM <i>→</i> Walt Disney Family Museum</div>':'<div class="result-kicker">NO RECIPROCAL RELATIONSHIP</div><div class="result-title small">THE CREDENTIAL REMAINS VALID.</div><div class="result-detail">Standard membership carries ASTC. This destination accepts ROAM.</div>'}
function ndc(e){const r=canvas.getBoundingClientRect();pt.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pt,cam)}
canvas.onpointerdown=e=>{if(S.done)return;ndc(e);if(ray.intersectObject(card).length){S.drag=true;S.auto=false;canvas.setPointerCapture(e.pointerId);ray.ray.intersectPlane(plane,hit);offset.copy(card.position).sub(hit);setPhase('dragging')}};canvas.onpointermove=e=>{if(!S.drag||S.done)return;ndc(e);ray.ray.intersectPlane(plane,hit);hit.add(offset);if(mobile){hit.x=THREE.MathUtils.clamp(hit.x,-.45,.45);hit.y=THREE.MathUtils.clamp(hit.y,layout.snap.y-.08,layout.start.y+.1)}else{hit.y=THREE.MathUtils.clamp(hit.y,-.5,.5);hit.x=THREE.MathUtils.clamp(hit.x,layout.start.x-.1,layout.snap.x+.08)}target.copy(hit)};canvas.onpointerup=e=>{S.drag=false;try{canvas.releasePointerCapture(e.pointerId)}catch{}if(!S.done)setPhase('idle')};
function run(){reset();S.auto=true;setPhase('awareness')}q('#reset').onclick=reset;q('#auto').onclick=run;q('#debugToggle').onclick=()=>{S.debug=!S.debug;debug.hidden=!S.debug};document.querySelectorAll('[data-scenario]').forEach(x=>x.onclick=()=>{S.scenario=x.dataset.scenario;matCard.color.set(S.scenario==='family'?0x0c22e8:0x2c2c31);document.querySelectorAll('[data-scenario]').forEach(y=>y.classList.toggle('active',y===x));reset()});
function resize(){const r=stage.getBoundingClientRect();R.setSize(r.width,r.height,false);cam.aspect=r.width/r.height;cam.updateProjectionMatrix();const m=innerWidth<720;if(m!==mobile)layoutNow()}
function loop(t){resize();const g=gap();if(S.auto&&!S.done)target.lerp(layout.snap,.018);if(!S.done){const engaged=S.drag||S.auto;if(engaged&&g<1.35&&g>.78)setPhase('awareness');if(engaged&&g<=.78&&g>.42)setPhase('proximity');if(engaged&&g<=.42&&g>.16){setPhase('magnetic');target.lerp(layout.snap,THREE.MathUtils.clamp((.42-g)/.26,0,1)*.22)}if(engaged&&g<=.16){S.done=true;S.drag=S.auto=false;setPhase('comparing');if(S.scenario==='family'){target.copy(layout.snap);t0=t;setPhase('registered')}else{setArcs(true);const r=layout.snap.clone();mobile?r.y+=.22:r.x-=.22;target.copy(r);tReject=t;setPhase('resist')}}}card.position.lerp(target,.18);if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const d=target.clone().sub(card.position);card.rotation.x=THREE.MathUtils.lerp(card.rotation.x,mobile?d.x*.1:-d.y*.08,.12);card.rotation.y=THREE.MathUtils.lerp(card.rotation.y,mobile?0:d.x*.055,.12)}if(t0){const x=(t-t0)/1000;if(x>.18){core.visible=true;setPhase('continuing')}const p=THREE.MathUtils.clamp((x-.22)/.56,0,1);mobile?pathB.scale.y=Math.max(.001,p):pathB.scale.x=Math.max(.001,p);core.scale.setScalar(1+(x<.32?Math.sin(Math.PI*Math.min(1,x/.32))*.35:0));if(x>.82&&S.phase!=='revealed'){setPhase('revealed');show(true)}}if(tReject&&t-tReject>260&&S.phase!=='rejected'){setPhase('rejected');show(false)}if(mobile){pathA.position.y=card.position.y-.12;a.position.set(card.position.x-.28,card.position.y-1.01,.06)}else{pathA.position.set(card.position.x-.12,card.position.y+.04,.055);a.position.set(card.position.x+1.6,card.position.y+.04,.06)}if(S.debug)debug.innerHTML=`<div><span>STATE</span><strong>${S.phase.toUpperCase()}</strong></div><div><span>DISTANCE</span><strong>${g.toFixed(3)}</strong></div><div><span>SCENARIO</span><strong>${S.scenario.toUpperCase()}</strong></div><div><span>COMPATIBLE</span><strong>${S.scenario==='family'?'TRUE':'FALSE'}</strong></div>`;R.render(scene,cam);requestAnimationFrame(loop)}
layoutNow();requestAnimationFrame(loop);
