export const pilots = [
  {
    id: 'anamorphosis-paris', label: 'Anamorphosis · Paris', className: 'OPTICAL / SPATIAL',
    law: 'DISTORTED FIELD → CYLINDRICAL REFLECTOR → RECTIFIED LEGIBILITY',
    pairMembers: { a: 'DISTORTED FIELD', relation: 'CURVED REFLECTION', b: 'CYLINDRICAL REFLECTOR' },
    matching: 'The curved reflector resolves the distorted field into a legible registered form.',
    other: 'Both members remain valid, but the reflected form refuses legibility.',
    memorable: 'Meaning appears only inside the other member’s curved reflection.',
    archiveBoundary: 'Models documented catoptric cylindrical-mirror anamorphosis. The procedural field is not an archival artifact.',
  },
  {
    id: 'coupler-virginia', label: 'Coupler · Virginia', className: 'MECHANICAL / CONTACT / LOAD',
    law: 'APPROACH → ROTARY HOOK CONTACT → CATCH / LOCK → SHARED LOAD PATH',
    pairMembers: { a: 'PIVOTING HEAD', relation: 'ROTARY HOOK / LATCH', b: 'MATING HEAD' },
    matching: 'Contact rotates the hook into a locked relation; subsequent pull transfers motion through the pair.',
    other: 'Both couplers remain valid, but the relation does not lock and load cannot transfer.',
    memorable: 'A touch becomes a mechanical relationship that carries force across the pair.',
    archiveBoundary: 'Pilot geometry is a bounded procedural interpretation of Eli H. Janney’s 1873 Alexandria patent mechanism, not a certified modern AAR coupler simulation.',
  },
  {
    id: 'ombak-bali', label: 'Ombak · Bali', className: 'TEMPORAL / RESONANCE',
    law: 'LOWER SOURCE + HIGHER SOURCE → FREQUENCY DIFFERENCE → SHARED BEAT ENVELOPE',
    pairMembers: { a: 'PENGUMBANG', relation: 'SHARED BEAT ENVELOPE', b: 'PENGISUP' },
    matching: 'Two close synthetic sources produce a stable audible and visible beating relation.',
    other: 'Each source remains valid alone, but the selected pair relation no longer produces the intended envelope.',
    memorable: 'A third temporal experience exists between the sources and disappears if either member is removed.',
    archiveBoundary: 'Uses synthetic tones to model documented paired-tuning / ombak mechanics. No archive recording is reproduced and no universal Bali-wide beat rate is claimed.',
  },
  {
    id: 'kento-japan', label: 'Kento · Japan', className: 'PRINT / REGISTRATION / TRANSFER',
    law: 'WOODBLOCK KENTŌ → REGISTRATION / PRESS → RECEIVING SHEET TRANSFER',
    pairMembers: { a: 'WOODBLOCK / KENTŌ', relation: 'REGISTRATION + PRESS', b: 'RECEIVING SHEET' },
    matching: 'The block-side kentō and receiving sheet agree before pressure transfers the procedural layer.',
    other: 'Both cards remain valid, but pressure transfers the layer off-register.',
    memorable: 'The cards separate after pressure and the receiving sheet reveals whether the pair truly registered.',
    archiveBoundary: 'Mechanism is grounded in institutional descriptions of kentō registration. Geometry and transferred marks are procedural; no specific historical artwork is reproduced.',
  },
  {
    id: 'stereoscopy-uk', label: 'Stereoscopy · UK', className: 'OPTICAL / DISPARITY / DEPTH',
    law: 'LEFT VIEW CARD + RIGHT VIEW CARD → CONTROLLED DISPARITY / FUSION → BINOCULAR DEPTH',
    pairMembers: { a: 'LEFT VIEW CARD', relation: 'CONTROLLED DISPARITY / FUSION', b: 'RIGHT VIEW CARD' },
    matching: 'Two archive-derived gallery views retain their difference while the controlled relation supports a stable depth reading.',
    other: 'Both views remain valid but their disparity refuses the intended fusion.',
    memorable: 'A spatial reading exists only because two flat view cards relate correctly.',
    archiveBoundary: 'Procedural paired gallery views are grounded in the same 1871 exhibition-room stereocard lineage used by V1; no archival raster is reproduced. Controlled viewpoint difference, not decorative 3D, drives the depth relation, and stereopsis is not required for comprehension.',
  },
  {
    id: 'signal-nigeria', label: 'Signal · Nigeria', className: 'SIGNAL / CARRIED LINK / REPEATER HANDOFF',
    law: 'LANLATE EARTH-STATION CAPTURE → CARRIED SIGNAL / REPEATER HANDOFF → IKORODU · OGIDO · ALABATA CHAIN',
    pairMembers: { a: 'LANLATE EARTH-STATION CARD', relation: 'CARRIED SIGNAL / REPEATER HANDOFF', b: 'IKORODU → OGIDO → ALABATA CHAIN' },
    matching: 'Lanlate capture establishes a carried path; the three source-backed repeater handoffs register before link output.',
    other: 'Both cards remain valid, but the handoff chain breaks before the final repeater can register the carried link.',
    memorable: 'A carried signal visibly leaves the earth-station card and only completes when the repeater chain on the other card responds.',
    archiveBoundary: 'Site names are source-backed. Routing, geometry, frequencies, hop timing and signal behavior remain illustrative rather than a certified historical engineering diagram.',
  },
  {
    id: 'astrolabe-isfahan', label: 'Astrolabe · Isfahan', className: 'CELESTIAL / RELATIVE ROTATION / READING',
    law: 'RETE / STAR MAP → SHARED AXIS + RELATIVE ROTATION → LATITUDE PLATE / LOCAL HORIZON',
    pairMembers: { a: 'RETE / STAR MAP', relation: 'SHARED AXIS / RELATIVE ROTATION', b: 'LATITUDE PLATE / LOCAL HORIZON' },
    matching: 'The documented star-map layer rotates against the local latitude plate and supports a structural horizon reading.',
    other: 'A different valid latitude plate changes the horizon relation without invalidating either member.',
    memorable: 'The celestial reading changes continuously because one real instrument layer rotates against another.',
    archiveBoundary: 'Structural translation of the documented rete ↔ latitude-plate subsystem of a Persian planispheric astrolabe. It is not a complete astronomical calculator; procedural geometry is used in the interactive scene.',
    controlMode: 'astrolabe',
  },
  {
    id: 'funicular-valparaiso', label: 'Funicular · Valparaíso', className: 'TRANSPORT / COUNTERWEIGHT / INVERSE MOTION',
    law: 'CAR A ↔ SHARED FUNICULAR / INVERSE POSITION ↔ CAR B',
    pairMembers: { a: 'FUNICULAR CAR A', relation: 'SHARED COUNTERWEIGHT / INVERSE POSITION', b: 'FUNICULAR CAR B' },
    matching: 'Not binary: manipulating either car immediately produces the exact inverse positional response in the other.',
    other: 'Alternate starting positions are also valid; the relation remains active under role reversal.',
    memorable: 'Move either member and the other answers at once in the opposite direction.',
    archiveBoundary: 'Structural translation of the documented two-car Valparaíso funicular relation. It does not model traction power, passenger load, braking force, cable tension or engineering performance.',
    controlMode: 'funicular',
  },
  {
    id: 'music-box-sainte-croix', label: 'Music Box · Sainte-Croix', className: 'MECHANICAL MEMORY / ENCODE / DECODE',
    law: 'PINNED CYLINDER → PIN-TO-TOOTH CONTACT → TUNED COMB RESPONSE',
    pairMembers: { a: 'PINNED CYLINDER / STORED SEQUENCE', relation: 'PIN-TO-TOOTH CONTACT', b: 'TUNED COMB / PHYSICAL DECODER' },
    matching: 'Engaged manual rotation carries editorial pin geometry into deterministic comb-tooth responses.',
    other: 'A second editorial cylinder remains valid and produces a different ordered contact sequence through the same relation.',
    memorable: 'Stored geometry on one member becomes ordered physical events only when the other member decodes it.',
    archiveBoundary: 'Grounded in the documented Swiss cylinder-music-box cylinder ↔ tuned-comb mechanism. Manual rotation, simplified pin maps, tooth count and any future audio are editorial interaction proof, not authentic Paillard tuning or historical music.',
    controlMode: 'music-box',
  },
  {
    id: 'boulle-france', label: 'Boulle · France', className: 'MATERIAL / RECIPROCAL CUT / INVERSION',
    law: 'STACKED MATERIAL FIELDS → ONE SHARED CUT → TWO RECIPROCAL INVERSE SURFACES',
    pairMembers: { a: 'PREMIÈRE-PARTIE MATERIAL FIELD', relation: 'ONE SHARED CUT / RECIPROCAL EXCHANGE', b: 'CONTRE-PARTIE MATERIAL FIELD' },
    matching: 'One shared cut is separated and reciprocally exchanged so both distinct material fields resolve as inverse surfaces.',
    other: 'Both material fields remain valid, but different cuts cannot resolve as one reciprocal partie / contrepartie map.',
    memorable: 'One division creates two opposite results at once; remove either member and reciprocity disappears.',
    archiveBoundary: 'Grounded in museum descriptions of Boulle première-partie / contre-partie production logic. Geometry and materials are procedural; no wildlife material or exact fabrication recipe is reproduced.',
  },
  {
    id: 'khipu-peru', label: 'Khipu · Peru', className: 'RECORD / TENSION / STRUCTURAL REGISTER',
    law: 'CARRYING CORD → SHARED TENSION / ATTACHMENT → SECONDARY CORD + KNOT POSITION RESPONSE',
    pairMembers: { a: 'CARRYING CORD / RECORD FRAGMENT A', relation: 'SHARED TENSION / ATTACHMENT', b: 'SECONDARY CORD / RECORD FRAGMENT B' },
    matching: 'Shared tension settles the carrying and secondary cord structures into a stable attachment and knot-position register.',
    other: 'Both cord systems remain structurally valid, but their attachment and knot positions retain a visible residual.',
    memorable: 'A slack structural gap becomes ordered only when both cord systems share tension.',
    archiveBoundary: 'Structural-only procedural translation grounded in museum object descriptions. No numeric, linguistic, administrative or historical message decoding is claimed; restricted/reference-only images are not reproduced.',
  },
  {
    id: 'mate-bombilla-argentina', label: 'Mate + Bombilla · Argentina', className: 'FILTER / INSERTION / SELECTIVE PASSAGE',
    law: 'MATE PARTICLE MEDIUM → BOMBILLA INSERTION / PERFORATED FILTER → SELECTIVE PASSAGE + CONTAINMENT',
    pairMembers: { a: 'MATE / PARTICLE MEDIUM', relation: 'BOMBILLA INSERTION / PERFORATED FILTER', b: 'SELECTIVE PASSAGE / CONTAINMENT' },
    matching: 'The perforated bombilla enters the represented medium; liquid-path markers pass while particulate matter remains contained.',
    other: 'Both members remain valid, but an incomplete insertion does not establish the selective passage relation.',
    memorable: 'At the pair interface, one represented material passes while another visibly remains behind.',
    archiveBoundary: 'Structural translation of the mate-vessel ↔ perforated bombilla filtering subsystem. It is not the full social practice, a hydraulic model, or a national-exclusivity claim; procedural geometry is used by default.',
  },
  {
    id: 'service-benin', label: 'Service · Benin', className: 'TELECOM / CONTACT / SERVICE REGISTER',
    law: 'BÉNIN TELEPHONE-CARD MEMBER → REGISTERED CONTACT / SERVICE HANDOFF → PUBLIPHONE SERVICE WINDOW RESPONSE',
    pairMembers: { a: 'BÉNIN TELEPHONE-CARD MEMBER', relation: 'REGISTERED CONTACT / SERVICE HANDOFF', b: 'PUBLIPHONE / SERVICE-READER MEMBER' },
    matching: 'The two telecom members register one bounded contact relation and the opposite-member service window responds.',
    other: 'Both historical-object roles remain valid, but the editorial contact field stays offset and no service-window response registers.',
    memorable: 'A service state appears only after the card and reader become one registered pair.',
    archiveBoundary: 'Grounded in Archives nationales du Bénin Série J and the 1999 ITU Bénin telecom report. The card-reader pairing, contact geometry and line-window behavior are editorial relational reconstruction, not a documented historical operating procedure; no archive raster is reproduced.',
  },
  {
    id: 'food-toyama', label: 'Food · Toyama', className: 'PACKAGE / PRESSURE / REVEAL',
    law: 'PRESS / PACKAGE CONSTRAINT → ORDERED RELEASE RELATION → BAMBOO-LEAF FAN / REVEAL RESPONSE',
    pairMembers: { a: 'PRESS / PACKAGE-CONSTRAINT MEMBER', relation: 'ORDERED RELEASE / PRESSURE TRANSFER', b: 'BAMBOO-LEAF / REVEAL MEMBER' },
    matching: 'A documented pressed/wrapped package relation releases in order and the receiving member opens into a shared bamboo-leaf reveal.',
    other: 'Both package members remain valid, but an incomplete editorial release does not register the shared reveal.',
    memorable: 'The food register becomes visible only because one member releases the constraint that the other member answers.',
    archiveBoundary: 'Mechanism is grounded in MAFF and official Toyama process references for masu-zushi packaging, pressing and opening. Geometry is procedural only; no commercial package, archive image, food-safety claim or universal regional form is reproduced.',
  },
  {
    id: 'hika-ahi-aotearoa', label: 'Hika Ahi · Aotearoa', className: 'FRICTION / INTERFACE / EMBER',
    law: 'HIKA RECIPROCAL STROKE + GROOVED BASE RESISTANCE → SUSTAINED FRICTION RELATION → EMBER STATE AT THE INTERFACE',
    pairMembers: { a: 'HIKA / RUBBING MEMBER', relation: 'CONTROLLED FRICTION / GROOVE CONTACT', b: 'KAUAHI / GROOVED BASE MEMBER' },
    matching: 'Sustained bounded friction remains localized at the groove relation and produces an editorial ember witness at the shared interface.',
    other: 'Both tool members remain valid, but offset contact dissipates the represented heat and no ember register forms.',
    memorable: 'The ember belongs to neither object alone; it appears exactly where the two members work against each other.',
    archiveBoundary: 'Mechanism-level procedural translation grounded in Te Papa material on hika ahi. Te Papa object and archive media remain reference-only / All Rights Reserved and are not reproduced. No ritual, whakapapa, ceremonial, universal-Māori, practical ignition or survival-instruction claim is made.',
  },
];

export const pilotById = Object.fromEntries(pilots.map((pilot) => [pilot.id, pilot]));
