export const wave005Families = [
  {
    id: 'city-gatineau', label: 'City · Gatineau', className: 'TRANSIT / VALIDATION / CONTINUATION',
    law: 'ROUTE MEMBER A → REGISTERED VALIDATION SEAM → ROUTE CONTINUATION MEMBER B',
    pairMembers: { a: 'ROUTE / PASSAGE MEMBER A', relation: 'VALIDATOR / REGISTERED SEAM', b: 'ROUTE CONTINUATION MEMBER B' },
    matching: 'The procedural validation seam registers and the route visibly continues from Member A into Member B.',
    other: 'Both route members remain valid, but the seam stays offset and no cross-member traversal registers.',
    memorable: 'The path visibly leaves one card, crosses the registered seam and continues inside the other.',
    archiveBoundary: 'Grounded in current STO validation interaction vocabulary. This is procedural geometry only: no STO branding, fare account, entitlement, exact validator UI or operational fare-system claim is reproduced.',
  },
  {
    id: 'frida-coyoacan', label: 'Frida · Coyoacán', className: 'TRACE / REFLECTION / REGISTER',
    law: 'MIRROR / TRACE MEMBER → REFLECTED PATH / ORIENTATION → RECEIVING EASEL / REGISTER MEMBER',
    pairMembers: { a: 'MIRROR / TRACE SURFACE', relation: 'REFLECTED TRACE PATH', b: 'EASEL / RECEIVING REGISTER' },
    matching: 'The reflected trace leaves the mirror member and lands on the receiving easel register.',
    other: 'Both workspace members remain valid, but the reflected path misses the receiving register.',
    memorable: 'A trace exists as a relational path only when one documented workspace element answers the other.',
    archiveBoundary: 'Mechanism-level abstraction grounded in Museo Frida Kahlo documentation of mirror/easel/workspace elements. No likeness, painting, artwork, photograph or claim that one specific historical mirror projected onto one specific easel is reproduced.',
  },
  {
    id: 'textile-bonwire', label: 'Textile · Bonwire', className: 'TEXTILE / SELVEDGE / CONTINUATION',
    law: 'NARROW WOVEN STRIP A → SELVEDGE ALIGNMENT / INTERLACING → STRUCTURAL TEXTILE CONTINUATION B',
    pairMembers: { a: 'NARROW WOVEN STRIP A', relation: 'SELVEDGE ALIGNMENT / INTERLACING', b: 'NARROW WOVEN STRIP B' },
    matching: 'Aligned strip edges interlace across the seam and become one structural textile continuation.',
    other: 'Both woven strips remain valid, but their edge threads do not form the intended join.',
    memorable: 'Loose edge threads from two separate strips become a single load-bearing continuation at the seam.',
    archiveBoundary: 'Grounded in Bonwire/Asante narrow-strip weaving collection evidence. Procedural threads only; no named or meaning-bearing motif, royal/lineage symbolism or universal Asante meaning is reproduced or inferred.',
  },
  {
    id: 'zellige-fes', label: 'Zellige · Fès', className: 'CRAFT / CUT PROFILE / MATERIAL FIT',
    law: 'CUT ZELLIGE PROFILE A → MATERIAL FIT / SEATING RELATION → TESSELLATION CONTINUATION B',
    pairMembers: { a: 'CUT TILE PROFILE A', relation: 'MATERIAL FIT / SEATING', b: 'TESSELLATION FIELD B' },
    matching: 'The procedural cut profile seats cleanly and transfers the tessellation rhythm into the opposite member.',
    other: 'Both tile assemblies remain valid, but the relational profile exposes a visible fit conflict.',
    memorable: 'One cut piece physically settles into the seam and makes the continuation belong to both assemblies.',
    archiveBoundary: 'Grounded in Fès zellij cut-and-assembly evidence. No historic panel, protected decorative composition, spiritual meaning or symbolic motif is reproduced; all geometry is procedural.',
  },
  {
    id: 'swell-marshall', label: 'Swell · Marshall', className: 'NAVIGATION MEMORY / WAVE / REFRACTION',
    law: 'SWELL VECTOR A → ISLAND / CHART RELATION → DEFLECTED / REFRACTED WAVE RESPONSE B',
    pairMembers: { a: 'INCOMING SWELL VECTOR FIELD', relation: 'ISLAND / CHART RELATION', b: 'DEFLECTED WAVE FIELD' },
    matching: 'The bounded wave field reorganizes around the island relation and the opposite member carries the deflected response.',
    other: 'Both wave fields remain coherent, but the intended relational deflection does not register.',
    memorable: 'An invisible environmental relationship becomes visible as one wavefront changes because it crosses the pair.',
    archiveBoundary: 'Mechanism-level translation of institutional stick-chart evidence. No specific historic chart, route, bearing, navigation tutorial or actionable wayfinding instruction is reconstructed.',
  },
  {
    id: 'siku-bolivia', label: 'Siku · Bolivia', className: 'MUSICAL PAIR / INTERLOCK / COMPLEMENT',
    law: 'IRA NOTE SET A + ARCA COMPLEMENT B → ALTERNATING INTERLOCK → SHARED PHRASE',
    pairMembers: { a: 'IRA / PARTIAL NOTE SET', relation: 'ALTERNATING INTERLOCK', b: 'ARCA / COMPLEMENTARY NOTE SET' },
    matching: 'The two incomplete event sets alternate into one bounded shared phrase.',
    other: 'Both instrument members remain valid, but their event gaps do not resolve into the selected interlock.',
    memorable: 'The phrase is visibly incomplete on either side and exists only through alternating contribution.',
    archiveBoundary: 'Grounded in museum and scholarly descriptions of complementary paired siku/panpipe interlock. Visual events are procedural; no authentic melody, archive recording, gender/cosmology/ritual claim or universal Bolivian/Andean practice is reproduced.',
  },
  {
    id: 'metate-teotitlan', label: 'Metate · Teotitlán', className: 'MATERIAL / ABRASION / CUMULATIVE TRACE',
    law: 'MANO / APPLIED STROKE A → PRESSURE + ABRASION INTERFACE → CUMULATIVE GRIND TRACE B',
    pairMembers: { a: 'MANO / STROKE MEMBER', relation: 'PRESSURE / ABRASION INTERFACE', b: 'METATE / CUMULATIVE TRACE MEMBER' },
    matching: 'Bounded reciprocal contact produces a visible cumulative abrasion trace on the receiving surface.',
    other: 'Both stone members remain valid, but offset contact does not accumulate the selected trace.',
    memorable: 'The material record grows only because the two members repeatedly work against one another.',
    archiveBoundary: 'Mechanism-only procedural translation grounded in Teotitlán/Oaxaca metate-mano collection context. It is not a food-preparation tutorial, recipe, efficiency claim, gender/household claim or universal Oaxaca practice; no collection raster is reproduced.',
  },
  {
    id: 'tongiaki-tonga', label: 'Tongiaki · Tonga', className: 'MARITIME / DOUBLE HULL / STRUCTURAL COUPLING',
    law: 'HULL A + HULL B → SPACING / CROSS-DECK COUPLING → COORDINATED STABILITY RESPONSE',
    pairMembers: { a: 'DOUBLE-HULL MEMBER A', relation: 'SPACING / CROSS-DECK COUPLING', b: 'DOUBLE-HULL MEMBER B' },
    matching: 'The two hull members are coupled across the deck relation and answer the bounded wave state together.',
    other: 'Both hull members remain valid, but spacing/coupling does not form the shared platform response.',
    memorable: 'Two independent hull responses become one coordinated platform response only after structural coupling.',
    archiveBoundary: 'Grounded in institutional tongiaki double-hull/joined-deck evidence. Procedural geometry only; no Te Papa raster, sailing/navigation instruction, safety or engineering-performance claim, hydrodynamic simulation, or unsupported ceremonial meaning is reproduced.',
  },
  {
    id: 'garamut-sepik-ramu', label: 'Garamut · Sepik / Ramu', className: 'PERCUSSION / IMPACT / EVENT TRACE',
    law: 'BEATER / ORDERED IMPACT A → SLIT-GONG MATERIAL RESONANCE → TEMPORAL EVENT TRACE B',
    pairMembers: { a: 'BEATER / IMPACT MEMBER', relation: 'MATERIAL RESONANCE CONTACT', b: 'SLIT-GONG / EVENT-TRACE MEMBER' },
    matching: 'A bounded editorial impact relation produces an ordered visual event trace across the pair.',
    other: 'Beater and resonant body remain valid, but the selected event order does not register.',
    memorable: 'Physical contact leaves a temporal trace that disappears if either implement or resonant body is removed.',
    archiveBoundary: 'Grounded in museum slit-gong/garamut object and impact evidence. Event order is editorial only; no community-specific message meaning, ritual, ancestor/clan content, archive audio, carving or object image is reproduced or decoded.',
  },
];

export const wave005Ids = new Set(wave005Families.map((family) => family.id));
